### ISSUE TITLE
Paypal sample returning 400 error...

### ISSUE THREAD

**Issue by skdutta-ga** [aspnet/AspNetWebHooks#31] opened 2018-10-08 03:15 UTC
I tried to run the PayPal sample code by using the nuget library for the PayPal webhooks instead of compiling the entire source. Compilation goes alright but every time I try to run it it is showing 400 error. I am using ngrok and testing with the PayPal simulator. 

I tried many things but getting the same error. Github sample code works fine. Here is my code in the dropbox in case anyone wants to try it out. 

https://www.dropbox.com/s/n0f6v7ffkym6wow/Webhook.zip?dl=0

**Comment by dougbu** [comment] 2018-11-01 22:40
Please describe exactly what is not working and when it isn't working. For example, if the sample works fine and your project does not, there's likely an error in your code.

**Comment by dougbu** [comment] 2018-11-27 22:44
Thank you for your feedback. We're closing this issue as no updates have been provided in a timely manner and we have been unable to reproduce the issue. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Closed by dougbu** 2018-11-27 22:44 UTC
