### ISSUE TITLE
Trello Webhooks request can not be verified

### ISSUE THREAD

**Issue by duhovich** [aspnet/AspNetWebHooks#28] opened 2018-05-15 19:13 UTC
I created a project with TrelloReceiver and deployed it on appharbor. In the file I wrote the following:
`<add key="MS_WebHookReceiverSecret_Trello" value="My Secret"/>`
And when the request comes, in the logs I see the following:
> The WebHook signature provided by the 'x-trello-webhook' header field does not match the value expected by the 'TrelloWebHookReceiver' receiver. WebHook request is invalid.

**Comment by dougbu** [comment] 2018-05-15 21:44
Hi. It looks like this is a question about how to use ASP.NET WebHooks. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the 'asp.net-webhooks' [tag](https://stackoverflow.com/questions/tagged/asp.net-webhooks).

If your question is not answered there, please provide more information about your specific scenario. For example, please examine the logging and / or attempt to debug the issue. See https://docs.microsoft.com/en-us/aspnet/webhooks/diagnostics/logging  for help there.

**Comment by dougbu** [comment] 2018-05-29 21:45
@duhovich were you able to get an answer on StackOverflow?

FYI we have an issue (#14) to create missing samples, including one for Trello. We would happily accept a PR filling that particular gap.

**Comment by dougbu** [comment] 2018-06-12 21:33
Thank you for your feedback. We're closing this issue as no updates have been provided in a timely manner and we have been unable to reproduce the issue. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Closed by dougbu** 2018-06-12 21:33 UTC
